# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHIS():
  def setup_method(self, method):
    if os.name == 'nt':  # Windows
        executable_path = './chromedriver.exe'
    else:  # Mac or other Unix-like systems
        executable_path = './chromedriver'
    service = Service(executable_path=executable_path)
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')
    self.driver = webdriver.Chrome(service=service, options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_HIS(self):
    self.driver.get("https://cgm.demo-de.cloud.c3.cgm.ag/cgmg3/")
    self.driver.fullscreen_window()
    self.driver.find_element(By.XPATH, "//input[@name='userName']").click()
    self.driver.find_element(By.XPATH, "//input[@name='userName']").send_keys("dmea_chir_azt2")
    self.driver.find_element(By.XPATH, "//input[@name='password']").send_keys("Dmea24")
    #self.driver.find_element(By.CSS_SELECTOR, "#btnLogin div").click()
    #self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(2) > .cgm-toggle-button > .ui-checkboxradio-label").click()
    #self.driver.find_element(By.CSS_SELECTOR, ".cgm-text-field").send_keys("Gernot")
    #self.driver.find_element(By.CSS_SELECTOR, ".cgm-text-field").send_keys(Keys.ENTER)
    #self.driver.find_element(By.CSS_SELECTOR, ".main-menu > .menu-link").click()
    #self.driver.find_element(By.CSS_SELECTOR, ".quick-menu-item:nth-child(1) > .menu-item").click()
    #element = self.driver.find_element(By.CSS_SELECTOR, ".quick-menu-item:nth-child(1) > .menu-item")
    #actions = ActionChains(self.driver)
    #actions.move_to_element(element).perform()
    #self.driver.find_element(By.CSS_SELECTOR, ".fancytree-focused .cgm-truncation").click()
    #self.driver.execute_script("window.scrollTo(0,0)")
    #self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(2) > .ng-scope:nth-child(1) > .ng-scope:nth-child(2) > .bedlocation:nth-child(1) span:nth-child(1) > .ng-binding:nth-child(2)").click()
    #self.driver.close()
  
